name: APIs.io Schemas
description: Browse JSON Schema definitions across the APIs.io network.
image: https://apis.io/assets/branding/apisio-social-card.png
url: https://schemas.apis.io

node: website
nav_active: more

keywords:
  - APIs
  - Search
  - Discovery

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "scripts"]
include: [".well-known"]

github_org: api-search
github_repo: schemas

collections:
  schemas:
    output: true
    permalink: /schemas/:path/

defaults:
  - scope:
      path: ""
      type: schemas
    values:
      layout: schema
